import type {
  AdminData,
  ChangeEvent,
  DashboardData,
  Letter,
  RagAnswer,
  ReviewItem,
  SavedView,
} from "@/lib/types";

const tianjinFindings: Letter["findings"] = [
  {
    id: "finding-process-validation",
    label: "01",
    title: "Process validation and lifecycle state of control",
    finding:
      "FDA described insufficient evidence that commercial API processes were supported by an adequate lifecycle validation program before distribution.",
    categories: ["Process Validation / PPQ / Continued Process Verification", "API Manufacturing / ICH Q7-related CGMP"],
    processLenses: ["Preventive", "Monitoring"],
    regulatoryReferences: ["FD&C Act § 501(a)(2)(B)", "ICH Q7 principles"],
    evidence: [
      {
        anchor: "observation-1-process-validation",
        section: "CGMP observations / Observation 1",
        excerpt:
          "Your firm failed to adequately demonstrate that the manufacturing process can reproducibly manufacture an API meeting its predetermined quality attributes.",
      },
    ],
    requestedActions: [
      "A detailed summary of the validation program for ensuring a state of control throughout the product lifecycle.",
      "A timeline for completing process performance qualification for marketed APIs.",
    ],
    comparisonQuestions: [
      "Are commercial APIs and processes supported by an approved lifecycle validation and PPQ strategy before distribution?",
      "Are continued process verification signals reviewed against defined alert and action criteria?",
    ],
    attentionLevel: "high",
    confidence: 0.97,
    reviewState: "approved",
  },
  {
    id: "finding-records",
    label: "02",
    title: "Master production and control records",
    finding:
      "FDA stated that master and batch production records did not consistently preserve the manufacturing detail needed to demonstrate traceability and control.",
    categories: ["Documentation / GDP / Batch Records", "Quality Unit / QA Oversight"],
    processLenses: ["Preventive", "Retrospective"],
    regulatoryReferences: ["FD&C Act § 501(a)(2)(B)"],
    evidence: [
      {
        anchor: "observation-2-records",
        section: "CGMP observations / Observation 2",
        excerpt:
          "Your master production instructions lacked complete details for critical manufacturing steps and associated process parameters.",
      },
    ],
    requestedActions: ["A remediation plan for master production instructions and executed batch documentation."],
    comparisonQuestions: [
      "Do approved master and batch records capture critical parameters, equipment, materials, and all manufacturing steps needed for reconstruction?",
    ],
    attentionLevel: "medium",
    confidence: 0.94,
    reviewState: "approved",
  },
  {
    id: "finding-stability",
    label: "03",
    title: "Stability program and retest support",
    finding:
      "FDA described gaps in the ongoing stability program and in the evidence supporting assigned retest periods.",
    categories: ["Stability / Expiry / Retest / Reserve Samples", "Laboratory Controls / Method Validation / Microbiology"],
    processLenses: ["Monitoring"],
    regulatoryReferences: ["FD&C Act § 501(a)(2)(B)"],
    evidence: [
      {
        anchor: "observation-3-stability",
        section: "CGMP observations / Observation 3",
        excerpt:
          "Your stability program did not include sufficient data to support the retest period assigned to distributed API batches.",
      },
    ],
    requestedActions: ["A comprehensive, independent assessment and remediation plan for the stability program."],
    comparisonQuestions: [
      "Does the stability program define stability-indicating methods, marketed configurations, commitments, attributes, time points, and retest justification?",
    ],
    attentionLevel: "medium",
    confidence: 0.92,
    reviewState: "approved",
  },
];

export const seedLetters: Letter[] = [
  {
    id: "7d90a73f-6465-4f6f-9c7f-f36b47317610",
    marcsCms: "731761",
    company: "Tianjin Kilo Pharmaceutical Sci-tech Co., Ltd.",
    country: "China",
    subject: "CGMP / Active pharmaceutical ingredients",
    issueDate: "2026-08-06",
    postedDate: "2026-08-18",
    issuingOffice: "Center for Drug Evaluation and Research",
    productClasses: ["Drugs"],
    drugSubtypes: ["API", "Non-sterile drug"],
    categories: [
      "Process Validation / PPQ / Continued Process Verification",
      "Documentation / GDP / Batch Records",
      "Stability / Expiry / Retest / Reserve Samples",
    ],
    regulations: ["FD&C Act § 501(a)(2)(B)", "FD&C Act § 704(a)(4)"],
    hasResponse: false,
    hasCloseout: false,
    reviewState: "approved",
    lifecycleState: "NEW",
    scopeStatus: "IN_SCOPE_DRUGS",
    executiveSummary:
      "FDA’s records review described deficiencies spanning API process validation, production documentation, analytical controls, ongoing stability, and establishment registration or drug listing. The approved synthesis separates the source-backed observations from internal comparison questions.",
    sourceUrl:
      "https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters/tianjin-kilo-pharmaceutical-sci-tech-co-ltd-731761-08062026",
    retrievedAt: "2026-08-29T00:42:18Z",
    sourceHash: "sha256:4e892c1d…bb731761",
    sourceVersion: "v1.0",
    facilityType: "API manufacturer",
    findings: tianjinFindings,
    lifecycle: [
      {
        id: "tl-1",
        type: "FIRST_SEEN",
        at: "2026-08-18T06:01:19Z",
        title: "First seen in FDA discovery feed",
        detail: "Listing row and canonical URL recorded in discovery snapshot DS-2026-08-18-02.",
        version: "discovery-1",
      },
      {
        id: "tl-2",
        type: "SCOPE_VERIFIED",
        at: "2026-08-18T06:03:08Z",
        title: "Drug scope verified",
        detail: "Canonical FDA metadata contained the exact class Drugs. Rule drugs-exact/v2 admitted the source.",
        version: "scope-v2",
      },
      {
        id: "tl-3",
        type: "AI_APPROVED",
        at: "2026-08-19T02:14:51Z",
        title: "Structured synthesis approved",
        detail: "Three findings and their source anchors passed grounding review and human approval.",
        version: "summary-v1",
      },
    ],
    originalSections: [
      {
        anchor: "document-metadata",
        heading: "Document metadata",
        paragraphs: [
          "Warning Letter · MARCS-CMS 731761 · Issue date 06 August 2026",
          "Product: Drugs · Center for Drug Evaluation and Research",
        ],
      },
      {
        anchor: "observation-1-process-validation",
        heading: "Observation 1 — Process validation",
        highlighted: true,
        paragraphs: [
          "Your firm failed to adequately demonstrate that the manufacturing process can reproducibly manufacture an API meeting its predetermined quality attributes.",
          "FDA requested a detailed summary of the validation program and a timeline for completing qualification activities for marketed APIs.",
        ],
      },
      {
        anchor: "observation-2-records",
        heading: "Observation 2 — Production records",
        paragraphs: [
          "Your master production instructions lacked complete details for critical manufacturing steps and associated process parameters.",
          "The source requested a retrospective assessment of records and a plan to ensure complete, contemporaneous production documentation.",
        ],
      },
      {
        anchor: "observation-3-stability",
        heading: "Observation 3 — Stability",
        paragraphs: [
          "Your stability program did not include sufficient data to support the retest period assigned to distributed API batches.",
          "FDA requested an independent assessment and remediation plan for the ongoing stability program.",
        ],
      },
      {
        anchor: "response-deadline",
        heading: "Response and conclusion",
        paragraphs: [
          "The letter requested a written response within the period stated by FDA and described the information expected for each corrective action.",
        ],
      },
    ],
    aiArtifacts: [],
    previewKind: "source-example",
  },
  {
    id: "53ee3b02-34cc-4110-a576-730122000001",
    marcsCms: "730122",
    company: "Suretec Innovations, LLC",
    country: "United States",
    subject: "Finished pharmaceuticals / CGMP",
    issueDate: "2026-08-13",
    postedDate: "2026-08-25",
    issuingOffice: "Office of Pharmaceutical Quality Operations",
    productClasses: ["Drugs", "Over-the-Counter Drugs"],
    drugSubtypes: ["Finished pharmaceutical", "OTC drug", "Non-sterile drug"],
    categories: ["Quality Unit / QA Oversight", "Laboratory Controls / Method Validation / Microbiology"],
    regulations: ["21 CFR 211.22", "21 CFR 211.160"],
    hasResponse: false,
    hasCloseout: false,
    reviewState: "auto_approved",
    lifecycleState: "NEW",
    scopeStatus: "IN_SCOPE_DRUGS",
    executiveSummary:
      "FDA described finished-drug CGMP concerns involving quality-unit oversight and laboratory controls. The source was admitted because canonical metadata explicitly included Drugs.",
    sourceUrl:
      "https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters/suretec-innovations-llc-730122-08132026",
    retrievedAt: "2026-08-25T07:17:44Z",
    sourceHash: "sha256:c410f6b2…aa730122",
    sourceVersion: "v1.0",
    facilityType: "Finished dosage manufacturer",
    findings: [
      {
        id: "suretec-quality",
        label: "01",
        title: "Quality unit oversight",
        finding: "FDA described inadequate quality-unit authority and oversight of CGMP activities.",
        categories: ["Quality Unit / QA Oversight"],
        processLenses: ["Preventive", "Monitoring"],
        regulatoryReferences: ["21 CFR 211.22"],
        evidence: [
          {
            anchor: "observation-1-quality-unit",
            section: "Observation 1",
            excerpt: "Your quality unit lacked adequate authority to fully exercise its responsibilities.",
          },
        ],
        requestedActions: ["A comprehensive assessment and remediation plan for quality-unit systems."],
        comparisonQuestions: [
          "Are quality-unit responsibilities, independent review, and approval authorities explicitly defined and evidenced?",
        ],
        attentionLevel: "high",
        confidence: 0.96,
        reviewState: "auto_approved",
      },
    ],
    lifecycle: [
      {
        id: "suretec-life-1",
        type: "FIRST_SEEN",
        at: "2026-08-25T06:00:44Z",
        title: "First seen",
        detail: "Candidate detected in the FDA listing export.",
      },
      {
        id: "suretec-life-2",
        type: "SCOPE_VERIFIED",
        at: "2026-08-25T06:02:31Z",
        title: "Drug scope verified",
        detail: "Product metadata normalized to Drugs and Over-the-Counter Drugs.",
      },
    ],
    originalSections: [
      {
        anchor: "document-metadata",
        heading: "Document metadata",
        paragraphs: ["Warning Letter · MARCS-CMS 730122", "Product: Drugs · Over-the-Counter Drugs"],
      },
      {
        anchor: "observation-1-quality-unit",
        heading: "Observation 1 — Quality unit",
        highlighted: true,
        paragraphs: ["Your quality unit lacked adequate authority to fully exercise its responsibilities."],
      },
    ],
    aiArtifacts: [],
    previewKind: "source-example",
  },
  {
    id: "11a77f9b-4107-4d30-a764-000000000301",
    marcsCms: "DEMO-301",
    company: "Northshore Sterile Products (illustrative)",
    country: "United States",
    subject: "Aseptic processing / sterility assurance",
    issueDate: "2026-07-19",
    postedDate: "2026-07-28",
    issuingOffice: "Office of Pharmaceutical Quality Operations",
    productClasses: ["Drugs"],
    drugSubtypes: ["Finished pharmaceutical", "Sterile drug"],
    categories: ["Aseptic Processing / Sterility Assurance / Media Fill", "Contamination Control / Cleaning / Disinfection"],
    regulations: ["21 CFR 211.113(b)", "21 CFR 211.42(c)(10)"],
    hasResponse: true,
    hasCloseout: false,
    reviewState: "pending",
    lifecycleState: "RESPONSE_ADDED",
    scopeStatus: "IN_SCOPE_DRUGS",
    executiveSummary:
      "Illustrative preview record showing how aseptic-processing observations, response documents, and pending review state appear in the portal.",
    sourceUrl: "https://www.fda.gov/",
    retrievedAt: "2026-08-28T21:02:13Z",
    sourceHash: "sha256:preview…000301",
    sourceVersion: "v1.1",
    facilityType: "Sterile finished dosage manufacturer",
    findings: [],
    lifecycle: [],
    originalSections: [],
    aiArtifacts: [],
    previewKind: "illustrative",
  },
  {
    id: "11a77f9b-4107-4d30-a764-000000000302",
    marcsCms: "DEMO-302",
    company: "Han River Analytical Services (illustrative)",
    country: "Republic of Korea",
    subject: "Laboratory controls / data integrity",
    issueDate: "2026-06-04",
    postedDate: "2026-06-17",
    issuingOffice: "Center for Drug Evaluation and Research",
    productClasses: ["Drugs"],
    drugSubtypes: ["Contract testing laboratory"],
    categories: ["Data Integrity / Computerized Systems / Audit Trail", "Laboratory Controls / Method Validation / Microbiology"],
    regulations: ["21 CFR 211.68", "21 CFR 211.194"],
    hasResponse: true,
    hasCloseout: true,
    reviewState: "approved",
    lifecycleState: "CLOSEOUT_ADDED",
    scopeStatus: "IN_SCOPE_DRUGS",
    executiveSummary: "Illustrative preview record for laboratory controls, data review, and a completed closeout lifecycle.",
    sourceUrl: "https://www.fda.gov/",
    retrievedAt: "2026-08-27T10:11:03Z",
    sourceHash: "sha256:preview…000302",
    sourceVersion: "v1.2",
    facilityType: "Contract testing laboratory",
    findings: [],
    lifecycle: [],
    originalSections: [],
    aiArtifacts: [],
    previewKind: "illustrative",
  },
  {
    id: "11a77f9b-4107-4d30-a764-000000000303",
    marcsCms: "DEMO-303",
    company: "Riverside Consumer Health (illustrative)",
    country: "Canada",
    subject: "OTC drug listing and labeling",
    issueDate: "2026-05-22",
    postedDate: "2026-06-02",
    issuingOffice: "Center for Drug Evaluation and Research",
    productClasses: ["Drugs", "Over-the-Counter Drugs"],
    drugSubtypes: ["OTC drug", "Registration/listing-focused enforcement"],
    categories: ["Drug Establishment Registration / Listing / NDC", "Packaging / Labeling / Container-Closure"],
    regulations: ["FD&C Act § 510(j)", "21 CFR Part 207"],
    hasResponse: false,
    hasCloseout: false,
    reviewState: "needs_revision",
    lifecycleState: "UPDATED",
    scopeStatus: "IN_SCOPE_DRUGS",
    executiveSummary: "Illustrative preview record for Drug listing, labeling, and a source-page update awaiting review.",
    sourceUrl: "https://www.fda.gov/",
    retrievedAt: "2026-08-26T05:41:53Z",
    sourceHash: "sha256:preview…000303",
    sourceVersion: "v1.1",
    facilityType: "OTC finished dosage manufacturer",
    findings: [],
    lifecycle: [],
    originalSections: [],
    aiArtifacts: [],
    previewKind: "illustrative",
  },
];

export const seedChanges: ChangeEvent[] = [
  {
    id: "event-1",
    letterId: seedLetters[1].id,
    company: seedLetters[1].company,
    eventType: "NEW",
    occurredAt: "2026-08-25T07:17:44Z",
    summary: "Drug scope verified and source version v1.0 admitted to review.",
  },
  {
    id: "event-2",
    letterId: seedLetters[2].id,
    company: seedLetters[2].company,
    eventType: "RESPONSE_ADDED",
    occurredAt: "2026-08-24T21:08:02Z",
    summary: "Recipient response linked as a child document; synthesis remains pending.",
  },
  {
    id: "event-3",
    letterId: seedLetters[4].id,
    company: seedLetters[4].company,
    eventType: "UPDATED",
    occurredAt: "2026-08-23T03:42:17Z",
    summary: "Canonical source hash changed; metadata unchanged; version v1.1 created.",
  },
  {
    id: "event-4",
    letterId: seedLetters[3].id,
    company: seedLetters[3].company,
    eventType: "CLOSEOUT_ADDED",
    occurredAt: "2026-08-20T13:20:00Z",
    summary: "Closeout letter linked and lifecycle view updated.",
  },
  {
    id: "event-5",
    letterId: seedLetters[0].id,
    company: seedLetters[0].company,
    eventType: "NEW",
    occurredAt: "2026-08-18T06:03:08Z",
    summary: "API warning letter admitted under exact Product: Drugs scope rule.",
  },
];

export const seedDashboard: DashboardData = {
  metrics: [
    { label: "New Drug letters", value: "08", delta: "+3 vs prior 30d", tone: "red", detail: "Posted in the last 30 days" },
    { label: "Source updates", value: "03", delta: "2 body · 1 metadata", tone: "ochre", detail: "New immutable versions" },
    { label: "Responses / closeouts", value: "05", delta: "3 / 2", tone: "green", detail: "Lifecycle documents added" },
    { label: "Pending review", value: "04", delta: "1 high attention", tone: "ink", detail: "Oldest item 11h" },
  ],
  changes: seedChanges,
  categoryTrends: [
    { label: "Quality Unit", value: 18, previous: 14 },
    { label: "Investigations", value: 15, previous: 17 },
    { label: "Laboratory", value: 13, previous: 10 },
    { label: "Validation", value: 11, previous: 8 },
    { label: "Data Integrity", value: 9, previous: 7 },
  ],
  subtypeDistribution: [
    { label: "Finished", value: 42 },
    { label: "API", value: 28 },
    { label: "OTC", value: 18 },
    { label: "Sterile", value: 12 },
  ],
  regulations: [
    { citation: "21 CFR 211.192", count: 14, change: "+4" },
    { citation: "21 CFR 211.22", count: 12, change: "+1" },
    { citation: "21 CFR 211.113(b)", count: 9, change: "+3" },
    { citation: "21 CFR 211.160", count: 8, change: "—" },
  ],
  health: [
    { name: "FDA discovery", status: "healthy", detail: "4,281 rows reconciled", checkedAt: "6 min ago" },
    { name: "Scope gate", status: "healthy", detail: "0 leakage indicators", checkedAt: "6 min ago" },
    { name: "AI validation", status: "attention", detail: "2 items routed to review", checkedAt: "12 min ago" },
    { name: "Retrieval index", status: "healthy", detail: "Source versions current", checkedAt: "9 min ago" },
  ],
  discovery: {
    lastSuccess: "29 Aug 2026 · 09:06 KST",
    nextRun: "29 Aug 2026 · 15:00 KST",
    recordsScanned: 4281,
    inScope: 684,
    exceptions: 2,
  },
};

export const seedRagAnswer: RagAnswer = {
  answer:
    "Across the indexed Drug warning-letter evidence, FDA’s recurring process-validation concerns cluster around three controls: demonstrating reproducibility before commercial distribution, retaining complete master and batch instructions, and maintaining continued verification with stability or process-trend evidence. The cited letter below directly supports those source facts. It does not establish a Daewoong gap or change a regulatory requirement.",
  interpretationLabel: "ai_synthesis",
  scopeLabel: "FDA Product: Drugs",
  filtersApplied: { category: "Process Validation / PPQ / Continued Process Verification", subtype: "API" },
  evidenceSufficiency: "sufficient",
  citations: [
    {
      id: "citation-1",
      letterId: seedLetters[0].id,
      company: seedLetters[0].company,
      title: seedLetters[0].subject,
      issueDate: seedLetters[0].issueDate,
      postedDate: seedLetters[0].postedDate,
      documentType: "Warning letter",
      anchor: "observation-1-process-validation",
      excerpt: tianjinFindings[0].evidence[0].excerpt,
      sourceUrl: seedLetters[0].sourceUrl,
      score: 0.94,
    },
    {
      id: "citation-2",
      letterId: seedLetters[0].id,
      company: seedLetters[0].company,
      title: "Production records",
      issueDate: seedLetters[0].issueDate,
      postedDate: seedLetters[0].postedDate,
      documentType: "Warning letter",
      anchor: "observation-2-records",
      excerpt: tianjinFindings[1].evidence[0].excerpt,
      sourceUrl: seedLetters[0].sourceUrl,
      score: 0.88,
    },
  ],
  generatedAt: "2026-08-29T00:55:09Z",
  requestId: "rag-preview-08f3",
  requestedModelProfile: "auto",
  effectiveModelProfile: "balanced",
  effectiveModelId: "preview-model",
  attemptedModelId: "preview-model",
  generationUsed: true,
};

export const seedReviewItems: ReviewItem[] = [
  {
    id: "review-1",
    summaryId: "summary-sterile-001",
    summaryRevision: 1,
    documentVersionId: "version-sterile-001",
    letterId: seedLetters[2].id,
    company: seedLetters[2].company,
    marcsCms: seedLetters[2].marcsCms,
    submittedAt: "2026-08-29T00:12:44Z",
    priority: "high",
    trigger: "High-impact aseptic category requires first-period human review",
    failedChecks: ["Requested action excerpt does not exactly match normalized anchor", "Confidence below 0.90"],
    sourceExcerpt:
      "The smoke study did not adequately demonstrate unidirectional airflow during a documented intervention near exposed sterile units.",
    aiFinding:
      "FDA determined that all aseptic interventions at the facility presented an unacceptable contamination risk.",
    sourceAnchor: "observation-2-airflow-study",
    categories: ["Aseptic Processing / Sterility Assurance / Media Fill"],
    confidence: 0.84,
    highAttention: true,
    relatedOpenItems: 1,
    state: "pending",
  },
  {
    id: "review-2",
    summaryId: "summary-otc-002",
    summaryRevision: 1,
    documentVersionId: "version-otc-002",
    letterId: seedLetters[4].id,
    company: seedLetters[4].company,
    marcsCms: seedLetters[4].marcsCms,
    submittedAt: "2026-08-28T18:31:08Z",
    priority: "normal",
    trigger: "Source version changed while structured extraction was in flight",
    failedChecks: ["Source-version consistency"],
    sourceExcerpt: "The listing information submitted for the identified products was incomplete.",
    aiFinding: "FDA stated that drug listing information was incomplete for the identified products.",
    sourceAnchor: "observation-1-listing",
    categories: ["Drug Establishment Registration / Listing / NDC"],
    confidence: 0.95,
    highAttention: true,
    relatedOpenItems: 1,
    state: "needs_revision",
  },
];

export const seedSavedViews: SavedView[] = [
  {
    id: "saved-1",
    name: "New finished pharmaceutical CGMP letters",
    description: "Newly posted finished-dosage Drug warning letters in the last 30 days.",
    criteria: { subtype: "Finished pharmaceutical", category: "CGMP" },
    filters: ["Posted ≤ 30 days", "Finished pharmaceutical", "CGMP"],
    cadence: "Off",
    alertState: "preview",
    resultCount: 8,
    lastMatched: "25 Aug 2026",
    owner: "Preview",
    openUrl: "/drug-letters?subtype=Finished+pharmaceutical&category=CGMP",
    updatedAt: "2026-08-25T00:00:00Z",
    isPreview: true,
  },
  {
    id: "saved-2",
    name: "API / process validation",
    description: "API letters with process validation, PPQ, or continued verification findings.",
    criteria: { subtype: "API", query: "process validation" },
    filters: ["API", "Process validation", "Preventive + Monitoring"],
    cadence: "Off",
    alertState: "preview",
    resultCount: 14,
    lastMatched: "18 Aug 2026",
    owner: "Preview",
    openUrl: "/drug-letters?subtype=API&q=process+validation",
    updatedAt: "2026-08-18T00:00:00Z",
    isPreview: true,
  },
  {
    id: "saved-3",
    name: "Quality Unit / 21 CFR 211.22",
    description: "Exact-term surveillance for Quality Unit authority and responsibilities.",
    criteria: { query: "21 CFR 211.22" },
    filters: ["21 CFR 211.22", "Quality Unit"],
    cadence: "Off",
    alertState: "preview",
    resultCount: 31,
    lastMatched: "25 Aug 2026",
    owner: "Preview",
    openUrl: "/drug-letters?q=21+CFR+211.22",
    updatedAt: "2026-08-25T00:00:00Z",
    isPreview: true,
  },
  {
    id: "saved-4",
    name: "Letters with closeout",
    description: "Lifecycle view for Drug letters with a newly linked closeout document.",
    criteria: { document: "closeout" },
    filters: ["Closeout added", "Lifecycle event"],
    cadence: "Off",
    alertState: "preview",
    resultCount: 6,
    lastMatched: "20 Aug 2026",
    owner: "Preview",
    openUrl: "/drug-letters?document=closeout",
    updatedAt: "2026-08-20T00:00:00Z",
    isPreview: true,
  },
];

export const seedAdmin: AdminData = {
  notification: {
    targetEmail: "grisellacrystabel@gmail.com",
    enabled: true,
    smtpDeliveryEnabled: false,
    smtpConfigured: false,
    queuedDeliveries: 0,
    failedDeliveries: 0,
  },
  corpus: {
    backfillYears: 3,
    activeRetentionYears: 5,
  },
  health: seedDashboard.health,
  queue: [
    { name: "scope-verification", depth: 0, oldest: "—", status: "Nominal" },
    { name: "document-processing", depth: 7, oldest: "4 min", status: "Nominal" },
    { name: "ai-validation", depth: 4, oldest: "11 h", status: "Attention" },
    { name: "notifications", depth: 1, oldest: "38 sec", status: "Nominal" },
    { name: "dead-letter", depth: 2, oldest: "18 h", status: "Review" },
  ],
  exceptions: [
    {
      id: "exc-2881",
      type: "AMBIGUOUS",
      source: "Canonical Product metadata",
      detectedAt: "29 Aug · 08:47 KST",
      detail: "Product label present but value node was empty; downstream publication withheld.",
    },
    {
      id: "exc-2879",
      type: "PARSE_FAILED",
      source: "Response PDF",
      detectedAt: "28 Aug · 23:11 KST",
      detail: "Text extraction confidence below threshold; OCR/manual review required.",
    },
  ],
  versions: [
    { component: "Drug scope rule", version: "drugs-exact/v2.0.0", activatedAt: "12 Aug 2026", status: "Active" },
    { component: "HTML parser", version: "fda-html/1.8.4", activatedAt: "24 Aug 2026", status: "Active" },
    { component: "Summary schema", version: "drug-summary/2.0.1", activatedAt: "19 Aug 2026", status: "Active" },
    { component: "Taxonomy", version: "pharma-findings/1.0.0", activatedAt: "19 Aug 2026", status: "Active" },
    { component: "Chunker", version: "structure-aware/1.3.0", activatedAt: "22 Aug 2026", status: "Active" },
  ],
  controls: [
    { control: "SCOPE-01 · deterministic Drug gate", status: "Passing", evidence: "684 active records · 0 leakage indicators" },
    { control: "DATA-04 · auth before retrieval", status: "Passing", evidence: "Cross-user suite passed · build 8a41" },
    { control: "AI-03 · evidence grounding", status: "Attention", evidence: "2 outputs correctly withheld" },
    { control: "BCP-02 · tested restore", status: "Passing", evidence: "Restore exercise · 18 Aug 2026" },
  ],
  lastRestoreTest: "18 Aug 2026 · successful",
  backupAge: "23 min",
};
