"""Regulatory Evidence Agent contract, validators, and bounded runner."""

from .contracts import (
    EvidenceAnchor,
    ExtractionWarning,
    ExtractionWarningCode,
    ProcessLens,
    QualitySystemCategory,
    RegulatoryFinding,
    RegulatoryFindingList,
    RegulatoryReference,
    RequestedAction,
)
from .gateway_adapter import RegulatoryGatewayError, RegulatoryMcpAnchorTools
from .interfaces import (
    AnchorObservation,
    PreauthorizedRegulatoryTools,
    RegulatoryAgentContext,
    RegulatoryAgentFailure,
    RegulatoryAgentResult,
    RegulatoryAgentSuccess,
    RegulatoryGenerationRequest,
    RegulatoryModelOutputProducer,
    RegulatoryRuntimeIdentity,
    RunFailureCode,
    RunLimits,
    SourcePin,
    ValidationCode,
    ValidationIssue,
)
from .runner import run_regulatory_evidence_agent
from .validation import (
    parse_regulatory_finding_list,
    sha256_text,
    validate_declared_output,
    validate_resolved_evidence,
)

__all__ = [
    "AnchorObservation",
    "EvidenceAnchor",
    "ExtractionWarning",
    "ExtractionWarningCode",
    "ProcessLens",
    "PreauthorizedRegulatoryTools",
    "QualitySystemCategory",
    "RegulatoryAgentContext",
    "RegulatoryAgentFailure",
    "RegulatoryAgentResult",
    "RegulatoryAgentSuccess",
    "RegulatoryFinding",
    "RegulatoryFindingList",
    "RegulatoryGenerationRequest",
    "RegulatoryGatewayError",
    "RegulatoryMcpAnchorTools",
    "RegulatoryModelOutputProducer",
    "RegulatoryReference",
    "RegulatoryRuntimeIdentity",
    "RequestedAction",
    "RunFailureCode",
    "RunLimits",
    "SourcePin",
    "ValidationCode",
    "ValidationIssue",
    "parse_regulatory_finding_list",
    "run_regulatory_evidence_agent",
    "sha256_text",
    "validate_declared_output",
    "validate_resolved_evidence",
]
