apiVersion: v1
kind: Namespace
metadata:
  name: fda-drug-intel
  labels:
    app.kubernetes.io/part-of: fda-drug-intel
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

